"""add_pending_questions_queue

Revision ID: 0acee5582538
Revises: 2b1f906a952a
Create Date: 2026-01-07 17:36:11.282371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0acee5582538'
down_revision: Union[str, None] = '2b1f906a952a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_state', sa.Column('pending_question_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_state', 'pending_question_ids')
    # ### end Alembic commands ###
