"""add_ai_responses_fields

Revision ID: 449064273927
Revises: 0acee5582538
Create Date: 2026-01-08 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '449064273927'
down_revision: Union[str, None] = '0acee5582538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_questions', sa.Column('feedback_text', sa.Text(), nullable=True))
    op.add_column('user_questions', sa.Column('hint_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_questions', 'hint_text')
    op.drop_column('user_questions', 'feedback_text')
    # ### end Alembic commands ###

